### ISSUE TITLE
Parse tree visualization

### ISSUE THREAD

**Issue by KOLANICH** [igordejanovic/parglare#106]
### Description

I guess `pglr` lacks a command to visualize a parse tree, like `java -cp antlr-4.8-complete.jar:. org.antlr.v4.gui.TestRig <grammar> <top rule> -gui ./test.txt` of ANTLR.

**Comment by igordejanovic** [comment]
This is now available in 0.14.0 in [`pglr parse` command](http://www.igordejanovic.net/parglare/latest/pglr/#parsing-inputs).

**Comment by KOLANICH** [comment]
Thank you.
