### ISSUE TITLE
Wrong positions with GLRParser and EMPTY

### ISSUE THREAD

**Issue by Hyldrean** [igordejanovic/parglare#110]
* parglare version: 0.12.1.dev13+gc0df483
* Python version: 3.5.3
* Operating System: Debian GNU/Linux 9 (stretch) 64 bits

### Description

The start/end positions are sometimes wrong when we use the GLRParser and grammar with EMPTY. NB: I couldn't reproduce the bug with the LR Parser. 

### What I Did

Here is a minimal working example
<pre lang=python><code>
from parglare import GLRParser, Grammar

rules = """
S: A A B;
A: letter;
B: letter | EMPTY;

terminals
letter: /\w/;
"""
g = Grammar.from_string(rules)
parser = GLRParser(g, build_tree=True, debug=False, debug_colors=True)
result = parser.parse("ab")
print(result[0].tree_str())
</code></pre>

It gives the tree
<pre><code>
S[0-><b>1</b>]
A[0->1]
  letter[0->1, "a"]
A[1->2]
  letter[1->2, "b"]
B[<b>1->1</b>]
</code></pre>

One can easily see that it's rather 
<pre><code>S[0-><b>2</b>]
A[0->1]
  letter[0->1, "a"]
A[1->2]
  letter[1->2, "b"]
B[<b>2->2</b>]
</code></pre>

**Comment by igordejanovic** [comment]
Thanks for the report. Could you make a PR with failing [regression test](https://github.com/igordejanovic/parglare/tree/master/tests/func/regressions)?

**Comment by Hyldrean** [comment]
It is the very first time I use py.test and I do a pull request. I hope all is fine.

**Comment by igordejanovic** [comment]
@Hyldrean It's perfect. Thanks!

**Comment by igordejanovic** [comment]
Fixed on master

**Comment by Hyldrean** [comment]
Thanks ! It works for me ;)
