### ISSUE TITLE
Expression syntax sugar

### ISSUE THREAD

**Issue by KOLANICH** [igordejanovic/parglare#19]
I have been translating some grammar in some syntax to parglare. That grammar had expression syntax. A user creates an expression template and gives it a name. Then he creates a special block where he just enumerates the operators tokens, their signature (unary, binary, where args are situated) and their priority and mentions the name of the template and the name of some name inside of that template. I think it may be a nice piece of syntax sugar for parglare.

**Comment by igordejanovic** [comment]
Not sure that I understand how it is done. parglare already supports declarative specification of associativity and priority. The pattern (i.e. the order of operands and operation) is easily specified by the production. Which part should be improved by your opinion?

**Comment by KOLANICH** [comment]
```
expressions {
  expr:  {
    ('-', %a) {3};
    (%a, '*', %b) {2};
  } <= foo | bar | expr; // in fact in the syntax I have met there was no `| expr`, but I guess requiring  specifying the recursion explicitly should give more flexibility
}
```
(the syntax is invented, the actual syntax I have met is different)

 should give something equivalent to

```
unaryMinus: "-" a=expr {3};
binaryMul: a=expr "*" b=expr {2};
exprTempl: foo | bar;
expr: exprTempl | unaryMinus | binaryMul;
```

Please note that I'm not familiar with grammars and parsers, I only was given a grammar and wanna get an AST. In process of translating I met the syntax similar to the one above and had to guess what does it mean and spend some time creating rules.

**Comment by igordejanovic** [comment]
I see. From my point of view using current parglare syntax is more readable and is well aligned with the way LR parsers work so I don't see any merit in making additional custom syntax. But, you could give it a try by making a grammar that will parse your syntax and produce Grammar object that would be fed to new Parser instance.

**Comment by igordejanovic** [comment]
I don't have intention/plan to implement something like this in parglare. Closing.
