### ISSUE TITLE
LAYOUT must allow empty match

### ISSUE THREAD

**Issue by alberth** [igordejanovic/parglare#24]
* parglare version: bc33add9eedbea64e5177fd716865cdb8360aa15 (Jan 27, 2018)
* Python version: 2.5.3
* Operating System: linux, ubuntu

### Description
The following specification breaks on missing whitespace at the start of the text:
``` python
from parglare import Grammar
from parglare import Parser

gram = """\
words : word | words word ;
word : /[a-z]+/ ;

LAYOUT : WS | comment ;
comment : /#.*/ ;
WS : /[ \t]+/ ;
"""

text = "abc def"

grammar = Grammar.from_string(gram)
parser = Parser(grammar)
result = parser.parse(text)
print(result)
```
produces
``` python traceback
Traceback (most recent call last):
  File "n.py", line 17, in <module>
    result = parser.parse(text)
  File "~/compiler3/parglare/parser.py", line 208, in parse
    position)
  File "~/compiler3/parglare/parser.py", line 475, in _skipws
    input_str, position, context=context)
  File "~/compiler3/parglare/parser.py", line 282, in parse
    nomatch_error(actions.keys()))
parglare.exceptions.ParseError: Error at position 1,0 => "*abc def". Expected: WS or comment
```
If you take out the `LAYOUT` and `comment` rules, it works. It looks like there is a forced `LAYOUT` at the start of the file. There may also be one at the end of the file, but that is not testable currently, I think.

I know forcing space between tokens is not normal in programming languages, as people tend to be afraid of using the spacebar and write code like `a+1-4=b`. However, the language I am parsing is a constrained natural language with sentences like `power-supply must provide power`. Optional white space doesn't make much sense there, and (I think) complicates parsing due to non-existing white-space ambiguities that must be resolved (words should never be broken into two pieces).

Depending on how you see this problem, several options to fix it exists (for as far as I can see):
* Note in the discussion of `LAYOUT` that it must allow to be empty.
* Don't require a `LAYOUT` at the start of the file, ie make it optional (the text might start with white-space, but not always).

Likely other options exist as well.

**Comment by igordejanovic** [comment]
If `LAYOUT` is not provided [`ws` setting](http://www.igordejanovic.net/parglare/parser/#ws) is used.
If `LAYOUT` is provided it **must** match between each token, including beginning and end of the input. I've added [a note in the docs](http://www.igordejanovic.net/parglare/grammar_language/#handling-whitespaces-and-comments-in-your-language). 

Controlling word boundaries is in parglare handled with a [special rule `KEYWORD`](http://www.igordejanovic.net/parglare/grammar_language/#handling-keywords-in-your-language) as the word boundary is not determined only by whitespaces. I think this mechanism should work in your case also.

**Comment by alberth** [comment]
I found the `WS` and `LAYOUT` explanation in the documentation already (which is quite good, I might add). The confusion part there is that the `WS` setting is also non-empty, and it doesn't fail to match before the first token (just like my example doesn't fail if you take out the `LAYOUT` rule). I guess there is a default `LAYOUT` rule that allows empty matches.

I agree that `KEYWORD` is an alternative, and I have used that currently, and made `LAYOUT` allow empty matches. Thank you for confirming that is the desired solution here.

**Comment by igordejanovic** [comment]
Chars in `ws` setting are always optional and they are used if `LAYOUT` is not defined. [This](https://github.com/igordejanovic/parglare/blob/master/parglare/parser.py#L473) is relevant part of the implementation.

**Comment by alberth** [comment]
Ah right, the code provides the optional matching rather than the pattern.

Looking at the code, I noticed the position is always incremented by 1. Does that mean my `WS` definition of `WS : /[ \t]+/ ;` is wrong, or at least non-efficient?

**Comment by igordejanovic** [comment]
No, your definition is perfectly fine. `WS` from your grammar is used in entirely different way. It has nothing to do with `ws` Parser param. You can call your rules in `LAYOUT` part of grammar anyway you like, only the entry rule must be called `LAYOUT`. Matching using grammar rules is done [here](https://github.com/igordejanovic/parglare/blob/master/parglare/parser.py#L541) using regex and string matches from terminal definitions. If the match succeeds the position is incremented by the length of the match, so your `WS` will greadilly consume all whitespaces ahead in one go.

**Comment by alberth** [comment]
thank you for the explanation
