### ISSUE TITLE
Definition of grammar and actions for loop behavior

### ISSUE THREAD

**Issue by KerryHolmes** [igordejanovic/parglare#39]
* parglare version: 0.5
* Python version: 3.6.3
* Operating System: Mac OSX High Sierra

### Description

I am trying to implement loop behavior, specifically a while loop using custom actions with my grammar. When I run the parser, it executes the statements before evaluating the loop conditions and then continues runs the loop with no loop body.

### What I Did

I defined the grammar as below:
PROGRAM:                STATEMENT_LIST;
@pass_nochange
STATEMENT_LIST:         STATEMENT STATEMENT_LIST?;
STATEMENT:              CONCEPT_STATEMENT
                      | EXPRESSION_STATEMENT
                      | ACCEPT_STATEMENT
                      | ANSWER_STATEMENT
                      | WHILE_STATEMENT
                      | IF_STATEMENT
                      | IMPORT_STATEMENT;
EXPRESSION_STATEMENT:   EXPRESSION_STATEMENT AND_OP EXPRESSION_STATEMENT {right, 1}
                      | EXPRESSION_STATEMENT OR_OP EXPRESSION_STATEMENT  {right, 1}
                      | EXPRESSION_STATEMENT GE_OP EXPRESSION_STATEMENT  {right, 2}
                      | EXPRESSION_STATEMENT LE_OP EXPRESSION_STATEMENT  {right, 2}
                      | EXPRESSION_STATEMENT GT_OP EXPRESSION_STATEMENT  {right, 2}
                      | EXPRESSION_STATEMENT LT_OP EXPRESSION_STATEMENT  {right, 2}
                      | EXPRESSION_STATEMENT EQ_OP EXPRESSION_STATEMENT  {right, 2}
                      | EXPRESSION_STATEMENT NE_OP EXPRESSION_STATEMENT  {right, 3}
                      | NOT_OP EXPRESSION_STATEMENT
                      | L_PAREN_PN EXPRESSION_STATEMENT R_PAREN_PN
                      | TAUTOLOGY
                      | CONTRADICTION
                      | IDENTIFIER
                      | NUMBER;
WHILE_STATEMENT:        WHILE_KW EXPRESSION_STATEMENT STATEMENT_LIST;

And the actions below:
actions_dict["PROGRAM"] = lambda _, nodes: nodes[0]
actions_dict["STATEMENT"] = lambda _, nodes: nodes[0]
actions_dict["EXPRESSION_STATEMENT"] = [lambda _, nodes: nodes[0] and nodes[2],
                                            lambda _, nodes: nodes[0] or nodes[2],
                                            lambda _, nodes: nodes[0] >= nodes[2],
                                            lambda _, nodes: nodes[0] <= nodes[2],
                                            lambda _, nodes: nodes[0] > nodes[2],
                                            lambda _, nodes: nodes[0] < nodes[2],
                                            lambda _, nodes: nodes[0] == nodes[2],
                                            lambda _, nodes: nodes[0] != nodes[2],
                                            lambda _, nodes: not nodes[1],
                                            lambda _, nodes: nodes[1],
                                            lambda _, nodes: bool(nodes[0]),
                                            lambda _, nodes: bool(nodes[0]),
                                            lambda _, nodes: nodes[0],
                                            lambda _, nodes: float(nodes[0])]
def while_func(context, nodes):
    print(nodes)
    while(nodes[1]):
        nodes[0]
    return None
actions_dict["WHILE_STATEMENT"] = while_func
actions_dict["ACCEPT_STATEMENT"] = lambda _, nodes: print("the answer is 42")

This parses the statement "WHILE 1==1  accept.request" correctly but when executing, It will print the answer once and then begin to execute the while loop with no output. I have tried executing the statement with and without the build tree flag but it gives the same behavior. I am looking for any advice on how to go about this.

**Comment by igordejanovic** [comment]
Hi Kerry,

Actions are executed during parsing, when a match is recognized. That's why you get one print, it happens when `accept.request` is parsed.
You are trying to evaluate the returned value of accept statement in the while loop. The return value is None (which is returned by accept_statement lambda). Thus, None gets evaluated in the loop.

What you can do is to return a function that do printing from the accept_statement actions and than call that function from the while loop. Something like:

```python
expression, statements = nodes[1], nodes[2]
while (expression):
   for statement in statements:
       statement()
```

**Comment by KerryHolmes** [comment]
Thanks, making `accept.request` return a function produces the expected behavior.
