### ISSUE TITLE
No valid parse on lexical ambiguity

### ISSUE THREAD

**Issue by brunocuervo** [igordejanovic/parglare#40]
* parglare version: 0.5
* Python version: 2.7.13
* Operating System: macOS 10.13.4

### Description

I'm migrating some basic NLP to parglare to test it, and bumped into this with some obscure regexes. It's probably not a happy case to have a space there, but I wanted to report it anyway. Here's a minimal version:

    grammar = r"""
    S: FOO | BAR;
    
    FOO: /a/ "foo";
    
    BAR: /a / "bar";
    """

    g = Grammar.from_string(grammar)
    GLRParser(g).parse('a foo')

This raises a ParseError: Error at position 1,2 => "a *foo". Expected: bar

I'm using the GLR parser since I need all possible parses (not that it would be useful with that example). Is there any way to get it to parse, without registering custom_lexical_disambiguation? (in case those regex recognizers are converted to literal strings, I don't even get the chance to fix it in the registered disambiguator)

**Comment by igordejanovic** [comment]
Looks like you `/a /` match won in the lexical disambiguation by longest match strategy. You can see it [here](https://github.com/igordejanovic/parglare/blob/master/parglare/parser.py#L654). It is implicit strategy that is favourable most of the time but in this case it is not as it seems. 
You might put the parser in debug mode (pass parameter `debug=True`) to verify.

`custom_lexical_disambiguation` must be registered if you want to override default behaviour. This might change in the future. E.g. setting `custom_lexical_disambiguation` to `False` might indicate that no disambiguation should take place. Please suggest if you have an idea how you would like it to work.

**Comment by brunocuervo** [comment]
Yeah, I saw debugging it that the longest match default strategy was forcing that token. At least in the GLR case, it seems like a good idea having a flag to indicate that no disambiguation should take place: in this example, I'm being forced to register a custom_lexical_disambiguation, and if there's ambiguity, raising a DisambiguationError so the GLR proceeds and finds the only valid parse in this case.

But there's something else in this example (sorry, looks like I mixed too much on the same issue): if the regex recognizers are changed to literal strings (ie `FOO: "a" "foo";` `and BAR: "a " "bar";`) there's no lexical ambiguity (get_tokens() only returns "a "). Is that the expected behavior in this case or am I missing something?

Thanks for the great work Igor.

**Comment by igordejanovic** [comment]
Yes. There is a scanning optimization in place that will favour string match with greater length.
You can see the logic [here](https://github.com/igordejanovic/parglare/blob/master/parglare/tables.py#L267).
`finish_flags` are used as a "cutoff" during scanning. This logic will order string matches at the beginning, from longest to shortest, after that it will try regexes. If string match succeeds it will try no other as this was the most specific match. This, again, is optimization for which there could be a flag for disabling in the future versions if needed. In computer language development, this is what is needed almost always, but I understand that in NLP it might not be.

**Comment by brunocuervo** [comment]
I see. I can get around it, but the possibility of disabling it for NLP (used in conjunction with the GLR parser) would be much appreciated.
Feel free to close the issue, we can open a feature request for this and a possible 'disable_lexical_disambiguation' flag if you think it's worth it.

**Comment by igordejanovic** [comment]
Yup. I think it won't hurt to have that flag. Feel free to register a new issue.
