### ISSUE TITLE
Add flag to disable lexical disambiguation

### ISSUE THREAD

**Issue by brunocuervo** [igordejanovic/parglare#41]
As discussed in #40, it would be useful to have a flag to disable lexical disambiguation (and maybe the scanning optimization for building the actions table [here](https://github.com/igordejanovic/parglare/blob/d9feec7e704aa7edf6de61112821cf5e98017a95/parglare/tables.py#L267)), for example to obtain all posible parses in NLP tasks with the GLR parser.

**Comment by igordejanovic** [comment]
Implemented via #86
