### ISSUE TITLE
Readme example needs update

### ISSUE THREAD

**Issue by rexroni** [igordejanovic/parglare#49]
* parglare version: 0.6.1
* Python version: 3.6.5
* Operating System: Archlinux

### Description

This is a cool project!  But I was miffed to find out that the readme example does not work.  It looks like on May 22 terminal symbols were given their own grammar block... that is probably what broke the example.

### What I Did

I copied the code from the readme into a python script and tried to run it.  I got this result:

```
ParseError: 9:8:";\nnumber: */\d+(\.\d+" => Expected: Name or StrTerm
```

Adding a line with the word `terminals` above the `number:...` line fixed the example.

**Comment by igordejanovic** [comment]
Thanks for the report. Yeah, I updated [the same example in the docs](http://www.igordejanovic.net/parglare/#quick-intro) but forgot for README :confused:
