### ISSUE TITLE
specify common action

### ISSUE THREAD

**Issue by dgreisen** [igordejanovic/parglare#6]
Feature request.

The `@` syntax for specifying common actions in the grammar is great. It would be really nice if I could specify my own common actions for use with the `@` syntax.

```parser = Parser(g, actions=actions, common_action=common_actions)```

If a key conflicts with a default common action (like collect), I'd like to override the default. (common actions should also be specified in documentation).

**Comment by igordejanovic** [comment]
Good idea.

Yeah, the docs needs to be updated before 0.4 release.

**Comment by igordejanovic** [comment]
Implemented on `develop` branch. Will be on `master` after some more testing.
Until the docs are updated see [the tests for this feature](https://github.com/igordejanovic/parglare/blob/b1f41c41bd5da95bdc5ca1b62a9f5bd47cb2eb20/tests/func/test_common_actions.py#L182). See also [the log message for the change](https://github.com/igordejanovic/parglare/commit/b1f41c41bd5da95bdc5ca1b62a9f5bd47cb2eb20).

Please test it from the `develop` branch and report if it's working for you.

**Comment by dgreisen** [comment]
It works very well. greatly simplifies my code.

**Comment by igordejanovic** [comment]
Great! I'll close the issue when docs are in place.
