### ISSUE TITLE
Parser accepts word when it shouldn't

### ISSUE THREAD

**Issue by SupraSummus** [igordejanovic/parglare#70]
* parglare version: rev ef27e8813455a9b26fb8af71a0d8a7f0d286f793
* Python version: 3.7
* Operating System: linux x86_64

### Description

Parglare seems to accept words from outside specified language. Grammar `s: "a" | EMPTY;` doesn't accept word "b". However parglare parses it successfully. 

### What I Did

```python
import parglare

grammar = parglare.Grammar.from_string('s: "a" | EMPTY;')
parser = parglare.Parser(grammar)
print(parser.parse("b"))
```

Output of listed program is `[]`. I would expect error to be raised.

**Comment by SupraSummus** [comment]
Of course this is user's fault. Adding `EOF` to the end of `s` fixes this problem.

I think `EOF` should be added by default implicitly. It seems more natural to me.

**Comment by SupraSummus** [comment]
This issue affects also example from main README (calculator). Fed with `34 && (a banana)` it evaluates it to be `34.0`. Even worse scenario is `34 – 5` = `34`.

Quick win is to fix this example, but what seems important to me is the fact that it's very easy to forget to add EOF. And then it may be tricky to detect malfunction. Like in the README.

@igordejanovic Taking it into account do you consider adding implicit EOF?

**Comment by igordejanovic** [comment]
Yes, It seems that it bites users way too often (like in #64)  so I agree it is better to add EOF  implicitly and do partial parse as a special case.

**Comment by igordejanovic** [comment]
This is not an issue anymore after EOF removal.
