### ISSUE TITLE
What about flake and CI?

### ISSUE THREAD

**Issue by SupraSummus** [igordejanovic/parglare#76]
* parglare version: rev ef27e8813455a9b26fb8af71a0d8a7f0d286f793
* Python version: NA
* Operating System: NA

### Description

It seems that flake8 checks are not triggered during Travis CI build. They are being triggered locally, when I call `tox`, and they return some errors but CI status is green. Is this intentional or not? In my opinion flake-correctness should be enforced by CI.

**Comment by igordejanovic** [comment]
No, it is not intentional. I fully agree that we should have flake8 check run by Travis.

**Comment by igordejanovic** [comment]
Closed via #77
