### ISSUE TITLE
feature request: colorize * in error report

### ISSUE THREAD

**Issue by dgreisen** [igordejanovic/parglare#8]
It would be hugely helpful if the * indicating where the parser failed were bright red. I hacked something together for arpeggio with regexp and http://click.pocoo.org/5/utils/#ansi-colors, but it would be great if this were built in to parglare.

**Comment by dgreisen** [comment]
While improving display, it would also be helpful to improve the debugger output:
* add color to the headings (token ahead:, context:, etc)
* indent and wrap text nicely using https://docs.python.org/2/library/textwrap.html
* add a hard return between each state so there is more visual definition

**Comment by igordejanovic** [comment]
Great idea. It should improve trace readability a lot. I try to keep dependencies low.
These deps could be optional (e.g. with fallback to current behaviour) and used only in development mode.

**Comment by dgreisen** [comment]
My understanding is that behind the scenes it's just adding special control
characters. You might just be able to grab [this function](
https://github.com/pallets/click/blob/master/click/termui.py#L335) and the
unstyle function and be good to go

**Comment by igordejanovic** [comment]
Yes, I guess you are right. click uses 3-clause BSD licence so it is compatible with MIT and shouldn't be a problem to take just the needed bits of code while keeping the copyright notice.

**Comment by igordejanovic** [comment]
@dgreisen This is implemented on the `master`. There is now a param `debug_colors` for `Parser`/`GLRParser` and `Grammar.from_string/from_file`. By default it is `False`.

For `pglr` command coloring is enabled by default. You can disable it by `--no-colors` switch. `click` module is now used to implement `pglr` cli so the command is changed a bit.
