### ISSUE TITLE
Option to write debug output into a file

### ISSUE THREAD

**Issue by alensuljkanovic** [igordejanovic/parglare#92]
Currently, once debug is enabled, output is printed into a console. Some IDE's can clip portion of the output due to restricted buffer size (most of them allow user to increase the buffer size, though).

Personally, I find it easier to navigate through file. I can, for example, delete a part of the content once I analyze it, and most importantly interpreter's output and parglare's debug output are not mixed.

**Comment by igordejanovic** [comment]
Do you have a problem redirecting stdout to a file?

**Comment by alensuljkanovic** [comment]
I wouldn't say it is a problem, but it adds a bit more code when running tests with pytest. For example,
I have to add another fixture to my test function, then at the end use that fixture to read the output and write it into a file manually. Code would look like this:

```python
def test_fnc(parser, capsys):
    code = "some code text"
    parser.parse(code, debug=True)

    # Needs to be added to read stdout
    captured = capsys.readouterr()
    with open("output.txt", "w") as f:
        f.write(captured.out)
```

Anyways, I just thought that it would be more elegant if parglare could just log into a file.

**Comment by igordejanovic** [comment]
Have you tried to run pytest from command line with `-s` switch and redirect the output to a file.
```
pytest -v -s mytests/* > output.log
```

**Comment by alensuljkanovic** [comment]
That actually works. I somehow misunderstood that part in pytest documentation. Thanks! I'll close the issue now.
